### ISSUE TITLE
Assertion when pressing special keys

### ISSUE THREAD

**Issue by CodeAsm** [CodeAsm/GameEngine#2]
```
gameengine: lib/imgui/imgui.cpp:6839: void ImGui::ErrorCheckEndFrameSanityChecks(): Assertion `g.IO.KeyMods == expected_key_mod_flags && "Mismatching io.KeyCtrl/io.KeyShift/io.KeyAlt/io.KeySuper vs io.KeyMods"' failed.
Aborted (core dumped)
```
Need repair/fix

**Comment by wmcnamara** [comment]
This is going to sound random, but thanks for opening this. I had the same issue and found this on google. Checking your commit helped me fix it. Thank you!

**Comment by CodeAsm** [comment]
Thanks for replying, it confirms why I even started opening issues and documenting my findings on my own code. It might actually help other people :smile:
